// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/definicoes" | "/entrar" | "/entrar/verificar" | "/financeiro" | "/grafico" | "/instrumento/[symbol]" | "/mercados" | "/noticias" | "/onboarding" | "/perfil" | "/portfolio" | "/recuperar" | "/recuperar/nova" | "/registar"
type AppRouteHandlerRoutes = "/api/contas" | "/api/ctrader/conta" | "/api/ctrader/estado" | "/api/ctrader/oauth/iniciar" | "/api/ctrader/oauth/retorno" | "/api/ctrader/oauth/sair" | "/api/ctrader/ordem" | "/api/ctrader/pendente" | "/api/ctrader/posicao" | "/api/ctrader/simbolo" | "/api/deriv/conta" | "/api/deriv/estado" | "/api/deriv/fechar" | "/api/deriv/oauth/iniciar" | "/api/deriv/oauth/retorno" | "/api/deriv/oauth/sair" | "/api/deriv/ordem" | "/api/deriv/proposta" | "/api/entradas" | "/api/motor/relatorio-revisao" | "/api/motores" | "/api/noticias" | "/api/preco/[symbol]" | "/api/push/enviar" | "/api/push/subscrever" | "/api/push/teste" | "/api/radar/[symbol]" | "/api/saldo" | "/api/saude" | "/api/sinais" | "/api/sinais/ocultar" | "/api/smt-referencia" | "/auth/confirmar"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/contas": {}
  "/api/ctrader/conta": {}
  "/api/ctrader/estado": {}
  "/api/ctrader/oauth/iniciar": {}
  "/api/ctrader/oauth/retorno": {}
  "/api/ctrader/oauth/sair": {}
  "/api/ctrader/ordem": {}
  "/api/ctrader/pendente": {}
  "/api/ctrader/posicao": {}
  "/api/ctrader/simbolo": {}
  "/api/deriv/conta": {}
  "/api/deriv/estado": {}
  "/api/deriv/fechar": {}
  "/api/deriv/oauth/iniciar": {}
  "/api/deriv/oauth/retorno": {}
  "/api/deriv/oauth/sair": {}
  "/api/deriv/ordem": {}
  "/api/deriv/proposta": {}
  "/api/entradas": {}
  "/api/motor/relatorio-revisao": {}
  "/api/motores": {}
  "/api/noticias": {}
  "/api/preco/[symbol]": { "symbol": string; }
  "/api/push/enviar": {}
  "/api/push/subscrever": {}
  "/api/push/teste": {}
  "/api/radar/[symbol]": { "symbol": string; }
  "/api/saldo": {}
  "/api/saude": {}
  "/api/sinais": {}
  "/api/sinais/ocultar": {}
  "/api/smt-referencia": {}
  "/auth/confirmar": {}
  "/definicoes": {}
  "/entrar": {}
  "/entrar/verificar": {}
  "/financeiro": {}
  "/grafico": {}
  "/instrumento/[symbol]": { "symbol": string; }
  "/mercados": {}
  "/noticias": {}
  "/onboarding": {}
  "/perfil": {}
  "/portfolio": {}
  "/recuperar": {}
  "/recuperar/nova": {}
  "/registar": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
