// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/definicoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/definicoes">> = Specific
  const handler = {} as typeof import("../../app/definicoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/entrar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entrar">> = Specific
  const handler = {} as typeof import("../../app/entrar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/entrar/verificar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entrar/verificar">> = Specific
  const handler = {} as typeof import("../../app/entrar/verificar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/financeiro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro">> = Specific
  const handler = {} as typeof import("../../app/financeiro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/grafico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grafico">> = Specific
  const handler = {} as typeof import("../../app/grafico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instrumento/[symbol]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instrumento/[symbol]">> = Specific
  const handler = {} as typeof import("../../app/instrumento/[symbol]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mercados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mercados">> = Specific
  const handler = {} as typeof import("../../app/mercados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/noticias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/noticias">> = Specific
  const handler = {} as typeof import("../../app/noticias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../app/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recuperar/nova/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar/nova">> = Specific
  const handler = {} as typeof import("../../app/recuperar/nova/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recuperar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar">> = Specific
  const handler = {} as typeof import("../../app/recuperar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/registar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registar">> = Specific
  const handler = {} as typeof import("../../app/registar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contas">> = Specific
  const handler = {} as typeof import("../../app/api/contas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/conta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/conta">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/conta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/estado/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/estado">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/estado/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/oauth/iniciar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/oauth/iniciar">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/oauth/iniciar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/oauth/retorno/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/oauth/retorno">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/oauth/retorno/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/oauth/sair/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/oauth/sair">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/oauth/sair/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/ordem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/ordem">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/ordem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/pendente/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/pendente">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/pendente/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/posicao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/posicao">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/posicao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ctrader/simbolo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ctrader/simbolo">> = Specific
  const handler = {} as typeof import("../../app/api/ctrader/simbolo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/conta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/conta">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/conta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/estado/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/estado">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/estado/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/fechar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/fechar">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/fechar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/oauth/iniciar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/oauth/iniciar">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/oauth/iniciar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/oauth/retorno/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/oauth/retorno">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/oauth/retorno/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/oauth/sair/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/oauth/sair">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/oauth/sair/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/ordem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/ordem">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/ordem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/deriv/proposta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deriv/proposta">> = Specific
  const handler = {} as typeof import("../../app/api/deriv/proposta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/entradas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entradas">> = Specific
  const handler = {} as typeof import("../../app/api/entradas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/motor/relatorio-revisao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/motor/relatorio-revisao">> = Specific
  const handler = {} as typeof import("../../app/api/motor/relatorio-revisao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/motores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/motores">> = Specific
  const handler = {} as typeof import("../../app/api/motores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/noticias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/noticias">> = Specific
  const handler = {} as typeof import("../../app/api/noticias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preco/[symbol]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preco/[symbol]">> = Specific
  const handler = {} as typeof import("../../app/api/preco/[symbol]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/push/enviar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/enviar">> = Specific
  const handler = {} as typeof import("../../app/api/push/enviar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/push/subscrever/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/subscrever">> = Specific
  const handler = {} as typeof import("../../app/api/push/subscrever/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/push/teste/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/teste">> = Specific
  const handler = {} as typeof import("../../app/api/push/teste/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/radar/[symbol]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/radar/[symbol]">> = Specific
  const handler = {} as typeof import("../../app/api/radar/[symbol]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/saldo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saldo">> = Specific
  const handler = {} as typeof import("../../app/api/saldo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/saude/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saude">> = Specific
  const handler = {} as typeof import("../../app/api/saude/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sinais/ocultar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sinais/ocultar">> = Specific
  const handler = {} as typeof import("../../app/api/sinais/ocultar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sinais/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sinais">> = Specific
  const handler = {} as typeof import("../../app/api/sinais/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/smt-referencia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/smt-referencia">> = Specific
  const handler = {} as typeof import("../../app/api/smt-referencia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/confirmar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/confirmar">> = Specific
  const handler = {} as typeof import("../../app/auth/confirmar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
